# Generated by Django 5.1.1 on 2024-09-29 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_rename_session_usermessage_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbotmessage',
            old_name='session',
            new_name='session_id',
        ),
    ]
