# Generated by Django 5.1.1 on 2024-09-29 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_rename_session_chatbotmessage_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbotmessage',
            old_name='session_id',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='usermessage',
            old_name='session_id',
            new_name='session',
        ),
    ]
