services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data

  ollama:
    image: ollama/ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: All
              capabilities: [gpu]
    volumes:
      - ../:/hackyeah2024  # Mount the parent HackYeah2024 directory using relative path
    ports:
      - "11434:11434"
    container_name: ollama
    entrypoint: ["/bin/bash", "/hackyeah2024/ollama-entrypoint.sh"]

volumes:
  esdata:
    driver: local
