version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data

  ollama:
    image: ollama/ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - ollama:/root/.ollama
      - ../:/hackyeah2024  # Mount the parent HackYeah2024 directory using relative path
    ports:
      - "11434:11434"
    runtime: nvidia
    container_name: ollama
    command: ["ollama", "create", "Lexi-Llama-3-8B-Uncensored_Q8_0.gguf", "-f", "/hackyeah2024/RAG-System/models/Lexi-Llama-3-8B-Uncensored_Q8_0.gguf"]  # Adjusted the file path

volumes:
  esdata:
    driver: local
  ollama:
    driver: local